# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Luca Colagrande <colluca@iis.ee.ethz.ch>

APP     = offloadTest
SRCS    = src/offloadTest.c
SRCS    += ../../../device/apps/axpyTest/src/axpyTest.c
INCDIRS = ../../../host/apps/offloadTest/src
INCDIRS += ../../../device/apps/axpyTest/src

include ../common.mk
