# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Luca Colagrande <colluca@iis.ee.ethz.ch>

APP     = offload
SRCS    = src/offload.c
SRCS    += ../../../device/apps/axpy/src/axpy.c
SRCS    += ../../../device/apps/gesummv/src/gesummv.c
SRCS    += ../../../device/apps/lu/src/lu.c
INCDIRS = ../../../host/apps/offload/src
INCDIRS += ../../../device/apps/axpy/src
INCDIRS += ../../../device/apps/gesummv/src
INCDIRS += ../../../device/apps/lu/src

include ../common.mk
